# Site settings
title: Your awesome title
email: info@awesome-site.com

permalink: pretty

quote: > # this means to ignore newlines until "baseurl:"
  Bacon ipsum dolor amet meatball cupim tenderloin
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://getaclue.github.io/mdl-jekyll" # the base hostname & protocol for your site

about_author_snippet: >
  Bacon ipsum dolor amet meatball cupim tenderloin frankfurter ham hock pork loin chuck kevin ham shankle capicola. Chuck prosciutto venison drumstick cow fatback picanha pig swine corned beef hamburger sirloin. Prosciutto fatback doner swine corned beef leberkas. Pancetta swine beef pastrami ground round spare ribs jerky bresaola brisket. Venison shank pork belly bresaola fatback. Sausage tenderloin tongue fatback ham hock spare ribs pork loin pork belly shoulder short loin corned beef ground round.

about_author_snippet_for_posts: >
  Bacon ipsum dolor amet meatball cupim tenderloin frankfurter ham hock pork loin chuck kevin ham shankle capicola.

# Social
twitter_username: jekyllrb
github_username:  jekyllrb
linkedin_username: jekyllrb

# Build settings
markdown: kramdown
